### ISSUE TITLE
Generated numbers not showing

### ISSUE THREAD

**Issue by DenisZ-t** [jamwaffles/Hidokaruuu#1]
I think hidoku does generate, but results are only shown in console (what`s more - only solved version). None of the buttons which appear on the website do anything.

**Comment by jamwaffles** [comment]
Hi, I haven't touched this code for a _very_ long time (6 years according to the Github UI!) so I can't remember what state I left this project in. I don't remember ever seeing it working though, so it would make sense that nothing shows up/works.
